### PR TITLE
Correcting method signatures in ts file

### LINKED ISSUE #148: Method signature with wrong type
https://github.com/Olical/EventEmitter/blob/1e2c824c0ddce1e73a6b2a8c0ebc912a08a811d6/EventEmitter.d.ts#L435

The signature of this method is incorrect - in the actual JS implementation 'args' is treated as an array element (not varargs). So, for a listener that accepts a single argument, you actually need to type `emitEvent('MyEvent', [foo])` rather than `emitEvent('MyEvent', foo)` as the TS signature suggests.

### PR DESCRIPTION
**Pull request by alexburlton**
Fixes #148

### CODE REVIEW

**Comment by Olical** [comment]
Thanks a lot! One more change required though because trigger is an alias to emitEvent, but the main change looks good to me. Thank you very much.

**Comment by alexburlton** [comment]
Ah yes good spot. Fixed that too now!

**Comment by Olical** [comment]
Sweet, thanks a lot! Big help!

**Comment by Olical** [comment]
Published under v5.2.6

**Pull request merged**
