### PR TITLE
Fix IIFE so webpack / babel works again

### LINKED ISSUE #109: unable to browserify + babelify v5
Attempts to browserify and babelify v5 fail while v4.2.0 succeeds.
Somehow `.call(this)` is converted to `.call(undefined)`

issue ticket which brought me here:
https://github.com/metafizzy/isotope/issues/976#issuecomment-218467528

### PR DESCRIPTION
**Pull request by Olical**
Should fix #109

### CODE REVIEW

**Comment by Olical** [comment]
It works for me locally with browserify and webpack.

**Comment by Olical** [comment]
This PR also fixes #111 now.

**Comment by Olical** [comment]
Yay, scope creep! :dancer:

**Comment by wwwouter** [comment]
It looks like this isn't part of version 5.1.0, is that correct?

**Comment by Olical** [comment]
Pretty sure it is. I can see it in the file.

**Comment by wwwouter** [comment]
You're absolutely right! I'm sorry!

**Pull request merged**
