### PR TITLE
fix(type): add missing args type for emit method

### PR DESCRIPTION
**Pull request by e-cloud**

### CODE REVIEW

**Comment by e-cloud** [comment]
@Olical hope to get review and merge ASAP, it's blocking the typescript compiler from running.

**Comment by Olical** [comment]
@e-cloud Would you like to depend on this repository and check that it's all working for you before I publish the package?

**Comment by e-cloud** [comment]
Yeah, I've used some of the apis, and i haven't found another mistyped method.

**Comment by Olical** [comment]
In v5.2.2, I hope it works!

**Comment by e-cloud** [comment]
thx

**Pull request merged**
