### PR TITLE
Fix `undefined` error in browser when compiled with Babel

### PR DESCRIPTION
**Pull request by williamukoh**
Provides a fallback for script to still work in browser, after compiling with Babel. Babel converts `this` to `undefined`

### CODE REVIEW

**Comment by Olical** [comment]
I was wondering why there were so many commits then I realised you targeted develop which I had forgotten about 😅 so you've updated develop for me I guess. Also didn't realise this was an issue, why is `this` not defined when you use babel + browser? I guess it gets wrapped in some object or function call that screws with it?

**Comment by williamukoh** [comment]
Was just following your instructions Sir!  --> `Contributing (aim your pull request at the develop branch!)` 

It  was kinda strange to me at first. I was using a gulp-babel setup to compile source JS files and noticed anytime I tried `new EventEmitter()`, I kept getting `undefined`. So I copied your source code `https://github.com/Olical/EventEmitter/blob/master/EventEmitter.js` and pasted into `https://babeljs.io/repl/`, and noticed argument passed to the self-executing anonymous function was changed from `this || {}` to `undefined || {}`

**Comment by Olical** [comment]
Yup, I know :D it's not a problem at all, just forgot it was that way. I'll update those things to how I like to do things now, thanks for reminding me.

I think I see your issue though and I think this fix is fine? I just hope it doesn't break it for anyone else. I'm guessing you have tried this version and it's all okay?

**Comment by williamukoh** [comment]
Yes I have. And it works fine. Doesn't break anything over here ;)

**Pull request merged**
