### PR TITLE
adding onAny and offAny functionality to be able to "catch" all events

### PR DESCRIPTION
**Pull request by Tomino2112**
This was really missing in our code where we needed to be able to handle some events separately, but just  "relay" most others

### CODE REVIEW

**Comment by Olical** [comment]
Why not just extend the class? You could then make it so that `emit` also `emits` a generic `eventEmitted` event which others can subscribe to. This avoids the special case. Also may as well aim PRs at master now, develop has fallen behind, although I should probably just update develop...

**Comment by Tomino2112** [comment]
Could do, just thought it would be good feature out of the box

**Comment by Olical** [comment]
I mean, maybe if a lot of people wanted it. But I said that before when all the method aliases were being added, then a few people chimed in so I added them. Which I regretted, a slightly longer method name is no big deal in exchange for clarity.

I honestly think this functionality works better as an event that is emitted internally, but I wouldn't want that by default for performance reasons. Hence why I think extension is the best route for this sort of thing. It's made to be extended :) it's plain ol' prototypical inheritance.

**Comment by Olical** [comment]
I'm going to close this for now. If people really want this for very good reasons I will consider it, but I'd rather stop adding to the API if I can. All it needs is add, remove and emit essentially. So the closer to that, the better. If you want more, extend it.

**Pull request closed without merging**
